### ISSUE TITLE
SketchPlane3d.through missing

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-geometry#105]
The function `SketchPlane3d.through` is missing. If I want to create a sketch plane from a point + direction I have to instead use `Plane3d.through` and then `Plane3d.fromPlane`.  

This is a minor inconvenience but it seems odd that `SketchPlane3d` can't do this directly.

**Comment by ianmackenzie** [comment]
Seems reasonable, but raises a few questions it would be great to hear your thoughts on:

- Is it sufficiently obvious in `SketchPlane3d.through point direction` that the given `direction` will be used as the _normal_ direction of the sketch plane, instead of its X or Y direction?
- Should `SketchPlane3d.withNormalDirection` be added too, for symmetry/consistency?
- What about `SketchPlane3d.throughPoints`? This is an interesting one since I don't think you'd want to just make it a shortcut for calling `Plane3d.throughPoints` and then `SketchPlane3d.fromPlane`. In the sketch plane case, you could tweak the logic a bit to ensure that the X direction of the sketch plane is equal to the direction from the first point to the second and the Y direction is chosen such that the third point has a positive Y component.

**Comment by MartinSStewart** [comment]
* I think it is obvious given that the documentation in `Plane3d.through` explains what it does: ` Construct a plane through the given point, with the given normal direction.` Additionally, if someone thought the direction parameter was for it's X or Y direction, they would probably pause and wonder how you control the rotation around that axis*.
* `SketchPlane3d.withNormalDirection` already exists? 
* `SketchPlane3d.throughPoints` also already exists?

**Comment by MartinSStewart** [comment]
Hehe, no worries. I look forward to the new version. 👍
