### ISSUE TITLE
BoundingBox2d.from missing in 2.0.0

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-geometry#107]
I noticed that BoundingBox2d.from is missing from the new release. I find this function useful, was it removed intentionally or was it an oversight?

**Comment by ianmackenzie** [comment]
It still exists! Just now as `Point2d.hull2` instead of `BoundingBox2d.from`. I did some refactoring of hull-type functions and moved a bunch of functions around; one of those changes I missed in the release notes because I was rushing a bit to get things published before elm-conf. I've updated the release notes; thanks for pointing this out and sorry for the confusion!

(I'll close this issue for now, but let me know if you think `BoundingBox2d.from` was a better name - I'm not 100% wedded to the new names/organization.)

**Comment by MartinSStewart** [comment]
Ah that explains it. I personally think it makes sense to have constructors for types in their respective modules but I haven't played around enough with the new setup to tell if this is more intuitive.

**Comment by ianmackenzie** [comment]
Hey @MartinSStewart I'm thinking of making some changes to the API:

- Rename `BoundingBox#d.hull*` to `BoundingBox#d.aggregate*`, with the exception of `BoundingBox#d.hull2` which will become `BoundingBox#d.union` (for conciseness, and for symmetry with `intersection`)
- Move `Point#d.hull*` to `BoundingBox#d.hull*`, with the exception of `Point#d.hull2` which will become `BoundingBox#d.from` again

So the API would look something like (units/coordinate systems omitted for simplicity):

```elm
module BoundingBox2d exposing (..)

from : Point2d -> Point2d -> BoundingBox2d
hull : Point2d -> List Point2d -> BoundingBox2d
hull3 : Point2d -> Point2d -> Point2d -> BoundingBox2d
hullN : List Point2d -> Maybe BoundingBox2d
hullOf : (a -> Point2d) -> a -> List a -> BoundingBox2d
hullOfN : (a -> Point2d) -> List a -> Maybe BoundingBox2d

union : BoundingBox2d -> BoundingBox2d -> BoundingBox2d
aggregate : BoundingBox2d -> List BoundingBox2d -> BoundingBox2d
aggregate3 : BoundingBox2d -> BoundingBox2d -> BoundingBox2d -> BoundingBox2d
aggregateOf : (a -> BoundingBox2d) -> a -> List a -> BoundingBox2d
aggregateOfN : (a -> BoundingBox2d) -> List a -> Maybe BoundingBox2d
```

This would make things closer to what they were before, with a few tweaks mostly to allow for the new functions that let you avoid `Maybe`s and reduce memory allocations when working with `List`s. Thoughts?

**Comment by MartinSStewart** [comment]
I do like that the constructors are located in the BoundingBox2d module, I think that makes it more discoverable. 

`hull3` and `aggregate3` seem redundant though. Can't the user write `BoundingBox2d.hull p0 [p1, p2]` and `BoundingBox2d.aggregate b0 [b1, b2]` instead?

**Comment by ianmackenzie** [comment]
Yeah, the only real reason `hull3` and `aggregate3` exist is for performance reasons - chaining `union` together allocates some unnecessary temporary bounding boxes, and even using `hull` means you have to allocate a temporary list. `hull3` and `aggregate3` can be written such that the only memory allocation is for the final result. And since bounding boxes will get used heavily in stuff like R-trees/octrees/bounding volume hierarchies to speed up picking/intersection checking etc., I wanted to make them as fast as possible. But it's a good point, I should mention something about this in the docs!

**Comment by MartinSStewart** [comment]
After thinking about it some more, wouldn't it be nicer if `union` was renamed to `aggregate2` for consistency?

**Comment by ianmackenzie** [comment]
I thought about that too, but there's an interesting (but probably not all that surprising, in retrospect) pattern where `foo2` versions of function families like `aggregate*` tend to have special, more 'normal' names:

- `BoundingBox2d.aggregate2` -> `BoundingBox2d.union`
- `BoundingBox2d.hull2` -> `BoundingBox2d.from`
- `Point2d.centroid2` -> `Point2d.midpoint`

(I also like the naming symmetry of `union` and `intersection`.)

**Comment by MartinSStewart** [comment]
Fair enough. I think one disadvantage with calling it `union` though is that the user might think it's doing a boolean union on the two bounding boxes. Still, I don't think it's worth changing the name over that since the type signature and documentation make it clear that isn't what's happening.
