### ISSUE TITLE
No way to deconstruct Point2d into Quantities

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-geometry#111]
There doesn't seem to be any function with this signature `Point2d u c -> (Quantity Float u, Quantity Float u)`. Instead there's `Point2d u c -> (Quantity Float u -> Float) -> (Float, Float)`. Why is that? At a glance it would seem like the former is safer as you're less likely to mix up the units. Also, in my specific use case it's also more convenient to be able to keep them as Quantities rather than convert them to Float.

**Comment by ianmackenzie** [comment]
Hey  @MartinSStewart, great question! It _was_ a deliberate decision, but one that I'm definitely still not entirely sure about. The primary reason is efficiency: in `elm-geometry` 1.x, the `Point2d` type was defined as

```elm
type Point2d
    = Point2d ( Float, Float )
```

which meant you could write

```elm
( x, y ) =
    Point2d.coordinates point
```

to deconstruct a `Point2d` into its X and Y coordinates, and this was efficient since it just ended up deconstructing the `( Float, Float )` that a `Point2d` was internally represented as. In `elm-geometry` 2.x, the most straightforward update would have been to change `Point2d` to be defined as:

```elm
type Point2d units coordinates
    = Point2d ( Quantity Float units, Quantity Float units )
```

which mean that you could indeed have written code like the above to deconstruct a `Point2d` into `x` and `y` `Quantity` values. However, the current definition of `Point2d` is actually

```elm
type Point2d units coordinates
    = Point2d { x : Float, y : Float }
```

instead, where `x` and `y` are defined to be values in the base `units` (e.g. values in meters or pixels, not feet or centimeters or whatever). The primary reason for this was to allow efficient interop with code that uses plain `Float` records to represent points/vectors; the above representation means that functions like

```elm
Point2d.fromPixels : { x : Float, y : Float } -> Point2d Pixels coordinates
Point2d.toMeters : Point2d Meters coordinates -> { x : Float, y : Float }
```

can be very efficient because in an `--optimize` build they're no-ops that just pass the record around without transforming or allocating anything. You only have to pay a conversion cost if you're not using base units in your non-`elm-geometry` code. (Records were chosen instead of tuples since they seem like the recommended approach currently - it helps that records, unlike tuples, work for `Vec4` and `Mat4` as well as for `Vec2` and `Vec3`).

Having this internal representation also means that non-optimized builds are a bit more efficient than with the tuple-of-quantities approach - you end up with a plain JavaScript object stored in a `Point2d` wrapper object, instead of additionally having a `Quantity` wrapper object for each field.

Unfortunately, this internal representation also means that a function like

```elm
Point2d.coordinates :
    Point2d units coordinates
    -> ( Quantity Float units, Quantity Float units )
```

would be inefficient since it would have to construct (allocate) a new tuple object from the `x` and `y` record fields, even though that would usually then just be deconstructed back into separate X and Y values. I expected accessing individual components to be the kind of things you would generally do in low-level, high-performance code, so I wanted to avoid potential performance footguns like that.

There _are_ the `xCoordinate` and `yCoordinate` functions for extracting coordinates separately, and these can be implemented efficiently because "wrap a `Float` in a `Quantity`" (unlike "construct a new tuple") is actually a no-op in optimized builds. So you can still access coordinates in a units-safe way, it's just more verbose than it might be.

Philosophically, I see accessing individual X and Y coordinates as a fairly low-level, somewhat unsafe thing to do anyways - I prefer to write as much code as possible in a [coordinate-free](http://www.dgp.toronto.edu/~karan/courses/418/notes/Coordfreegeom.pdf) way, since I find it leads to more expressive, more flexible and safer code. So making individual coordinate access more verbose seemed like a reasonably acceptable tradeoff.

Anyways, to me the main options seem to be:

- Leave everything as-is, use `xCoordinate` and `yCoordinate` where necessary, try to keep code coordinate-free where possible
- Add a `Point2d.coordinates : Point2d units coordinates -> ( Quantity Float units, Quantity Float units )` function for convenience, with a warning in the docs that it is a potential performance issue
- Change to an internal representation based on `( Quantity Float units, Quantity Float units )` to allow an efficient `Point2d.coordinates` implementation, at the cost of having more expensive interop with record-based code

Thoughts?

**Comment by MartinSStewart** [comment]
I thought that any custom types of the form `type MyType = MyType Float` would get converted to Float when using `--optimize`. Are you saying this isn't the case for `{ x = Quantity Float unit, y = Quantity Float unit }`? Otherwise it seems like returning `Quantity Float unit` would have the same performance as returning `Float` when running an optimized build.

However, even if returning `Quantity Float unit` is slower, has benchmarking been done for it? If it's only, say, 5% slower then I think the increased type safety of keeping the floats inside Quantity would be worth it. Or at least, it would be better to have that as the default and then have a function to lets you get the floats directly if the performance really matters.

For the options you listed, I think `Point2d.coordinate` is reasonable (along with adding it to `Vector2d` and any other relevant modules). That's basically what I've done in my project for the time being.

**Comment by MartinSStewart** [comment]
I'm currently working on upgrading my game from elm-geometry 1 to elm-geometry 2 and I've noticed now that sometimes it's quite useful to have `toTuple` return the raw floats. There are situations where I'm doing lots of math operations and verbosity of Quantity functions gets too unwieldy. So in other words, it's good to have both options.

**Comment by ianmackenzie** [comment]
If I understand correctly, `{ x : Float, y : Float }` and `{ x : Length, y : Length }` should end up having the same runtime representation (a JavaScript object with two number fields) when using `--optimize`, but I *don't* think that means there's actually a way to write Elm code to do zero-allocation conversions between those two types. For example, to convert from the former to the latter, you'd have to write some Elm code like

```elm
values =
    { x = 3
    , y = 4
    }

lengths =
    { x = Length.meters values.x
    , y = Length.meters values.y
    }
```

In theory when using `--optimize` the Elm compiler *could* look at this expression, see that the runtime representations of `lengths` and `values` are actually see the same, verify that I am indeed copying `x` to `x` and `y` to `y`, and then convert this into basically

```elm
lengths =
    values
```

but unless I am very much mistaken the Elm compiler doesn't do anything close to this level of optimization. Instead, I'm 99.9% sure that the above code will lead to an extra object allocation. Similarly if I had a `List Float` then I'd love to be able to write

```elm
lengths =
    List.map Length.meters values
```

and have the Elm compiler recognize that it can just reuse the existing list instead of allocating a new one, but I am quite sure that that is not the case.

What I might do is add `Point2d.coordinates`, `Vector2d.components` etc. that return `Quantity` tuples and then I can run some benchmarks comparing those to `xCoordinate`/`yCoorrdinate` and `toPixels`/`toMeters`. That will hopefully confirm my suspicions, and will be a nice thing to be able to reference in the docs.

**Comment by ianmackenzie** [comment]
Looks like my intuition may have been wrong - I added `Point#d.coordinates` (plus `coordinatesIn`), wrote a simple benchmark, and the tuple-based access doesn't actually seem to be meaningfully slower than accessing individual coordinates separately. I'll leave this open for now, though, since I still need to add some tests and add the corresponding `components` functions for vectors and directions.
