### ISSUE TITLE
Vector2d.direction returns invalid result for very small non-zero values

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-geometry#99]
The following prints out `Direction: Just (Direction2d (Infinity,Infinity))` when the expected behavior is to print out `Direction: Nothing`
```
_ =
    Vector2d.fromComponents ( 1.0e-200, 1.0e-200 )
        |> Vector2d.direction
        |> Debug.log "Direction"
```

**Comment by ianmackenzie** [comment]
Good catch! Looks like there's some floating-point underflow going on...might need a second check within `Vector2d.direction`, with some fallback logic for extremely small components.

I think it should be possible to actually return `Direction2d (0.7071..., 0.7071...)` in this case, by doing something like pre-dividing one of the two components by the other instead of doing a naive normalization.

**Comment by ianmackenzie** [comment]
Basically implement this: https://d3cw3dd2w32x2b.cloudfront.net/wp-content/uploads/2012/07/Vector-length-and-normalization-difficulties.pdf

**Comment by MartinSStewart** [comment]
I looked at the paper. If I'm not mistaken, it seems to introduce substantial errors into the length result? For example, the vector (2,1) has length `sqrt(2*2 + 1*1)` or `2.236...`. The paper says to divide each component by the largest component and then scale it back at the end.  So we get  `2 * sqrt(2*2 / 2 + 1*1 /2)` or `3.162...`.

**Comment by ianmackenzie** [comment]
I think what the paper is suggesting is (taking your example):

- divide both components by the largest component (2), giving the vector (1, 0.5)
- find the length of that scaled vector: sqrt(1 * 1 + 0.5 * 0.5) = 1.11803
- to find the direction of the original vector, divide the scaled (1, 0.5) vector by its length (1.11803) to get (0.89443, 0.44721)
- to find the length of the original vector, multiple the length of the scaled vector (1.11803) by the largest component of the original vector (2) to get 2.23607

This works, and avoids overflow and underflow when squaring the components. I've implemented this logic in e90e37a56e1a310653461b03ce88f3248d4a8de1 in the `coordinate-systems` branch, although while doing that I realized that `Vector#d.squaredLength` was also unsafe in the same kind of way (since it can return zero or infinity for finite-length vectors). I don't think saving a single square root is enough of a performance concern to really warrant a separate function, so I've removed `Vector#d.squaredLength` and related functions like `Point#d.squaredDistanceFrom` and `LineSegment#d.squaredLength`.

**Comment by MartinSStewart** [comment]
Oh duh, silly math mistake by me.  Thank you for implementing it. Do you have a time estimate on when the `coordinate-systems` branch will be merged into master? Just asking out of curiosity, there's no time pressure for my case.

I agree, Vector#d.squaredLength seems best to remove.

**Comment by ianmackenzie** [comment]
I think I'm getting close on the coordinate systems stuff - I want to do a bit of a revamp of the basic point/vector constructors (see #100) but otherwise it's mostly just documentation updates at this point (although that is a pretty big chunk of work in itself). I *do* need the new version of `elm-geometry` to be published well in advance of my talk at elm-conf in September, so I'd estimate some time in July =)

**Comment by MartinSStewart** [comment]
Very cool. I've had to write Point2d.fromCoordinates a lot, shortening it to Point2d.xy is a welcome improvement. Looking forward to the release and your talk!

**Comment by ianmackenzie** [comment]
Yeah, making that more compact was definitely a goal, especially now with the addition of units - without any changes you would have had to write
```elm
Point2d.fromCoordinates ( meters 2, meters 3 )
```
and now instead you'll be able to write
```elm
Point2d.xy (meters 2) (meters 3)
```
or even
```elm
Point2d.meters 2 3
```
(These are all assuming that you import functions like `meters` unqualified...in general I'm very strict about only ever using qualified imports, even for stuff like `Html`, but `meters` and `feet` and `pixels` is one place where I make an exception.)

**Comment by ianmackenzie** [comment]
Anyways, happy to keep the discussion going but I think I can now close this issue on the assumption that the `coordinate-systems` branch will be merged into `master` soon (I think it's well past the 'experiment' phase by now).
